# Generated by Django 4.0.1 on 2022-01-31 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0003_raw_recipe_cooking_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('meal_day', models.CharField(choices=[('su', 'Sunday'), ('mo', 'Monday'), ('tu', 'Tuesday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday'), ('sa', 'Saturday')], max_length=2, verbose_name='Day of Week for Meal')),
                ('meal_time', models.CharField(choices=[('bk', 'Breakfast'), ('lu', 'Lunch'), ('di', 'Dinner'), ('de', 'Dessert'), ('sn', 'Snack')], max_length=2, verbose_name='Meal Time')),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meals.mstr_recipe')),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Meal Plan Name')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_meals', models.ManyToManyField(to='cooks.plan_meal')),
            ],
        ),
    ]
