# Generated by Django 4.0.1 on 2022-02-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_alter_mstr_recipe_meal_id'),
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='selected_meals',
        ),
        migrations.AddField(
            model_name='plan',
            name='meals',
            field=models.ManyToManyField(blank=True, null=True, to='meals.mstr_recipe'),
        ),
        migrations.AddField(
            model_name='plan_meal',
            name='plan',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='cooks.plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan_meal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mstr_recipe'),
        ),
    ]
