# Generated by Django 4.0.1 on 2022-02-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0003_alter_plan_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_meal',
            name='meal_day',
        ),
        migrations.RemoveField(
            model_name='plan_meal',
            name='meal_time',
        ),
    ]
