# Generated by Django 4.0.1 on 2022-02-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0005_remove_plan_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_meal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_on_plan', to='cooks.plan'),
        ),
    ]
