# Generated by Django 4.0.1 on 2022-02-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_alter_mstr_recipe_meal_id_and_more'),
        ('cooks', '0006_alter_plan_meal_plan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan_meal',
            unique_together={('meal', 'plan')},
        ),
    ]
