# Generated by Django 4.0.1 on 2022-02-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0007_alter_plan_meal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_meal',
            name='would_make_again',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
