# Generated by Django 4.0.1 on 2022-02-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0008_plan_meal_would_make_again'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_meal',
            name='would_make_again',
        ),
        migrations.AddField(
            model_name='plan_meal',
            name='review',
            field=models.SmallIntegerField(default=0),
        ),
    ]
