# Generated by Django 4.0.1 on 2022-09-11 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0024_meal_item_mstr_recipe_list'),
        ('cooks', '0009_remove_plan_meal_would_make_again_plan_meal_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal_item')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mstr_recipe')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooks.plan')),
            ],
        ),
    ]
