# Generated by Django 4.0.1 on 2022-09-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0011_alter_plan_list_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan_list',
            options={'ordering': ['plan', 'meal']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='plan_list',
            order_with_respect_to=None,
        ),
    ]
