# Generated by Django 4.0.1 on 2022-09-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0012_alter_plan_list_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_list',
            name='got',
            field=models.BooleanField(default=False),
        ),
    ]
