# Generated by Django 4.0.1 on 2022-09-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0013_plan_list_got'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan_list',
            options={'ordering': ['plan', 'meal', 'item']},
        ),
        migrations.AddField(
            model_name='plan_list',
            name='uom',
            field=models.CharField(choices=[('qt', 'Qty'), ('ml', 'Mililiter'), ('ll', 'Liter'), ('ts', 'Tsp'), ('tb', 'Tbsp'), ('cu', 'Cup'), ('oz', 'Ounzes'), ('lb', 'Pounds')], default='qt', max_length=2, verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='plan_list',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=8),
        ),
    ]
