# Generated by Django 4.0.1 on 2023-01-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0015_alter_plan_list_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_list',
            name='uom',
            field=models.CharField(choices=[('qt', ''), ('ts', 'Tsp'), ('tb', 'Tbsp'), ('cu', 'Cup'), ('oz', 'Ounces'), ('lb', 'Pounds'), ('ml', 'Milliliter'), ('ll', 'Liter'), ('ea', 'Each'), ('dz', 'Dozen'), ('bu', 'Bunch'), ('st', 'Stalks'), ('cl', 'Cloves')], default='qt', max_length=2, verbose_name='Unit of Measure'),
        ),
    ]
