# Generated by Django 4.0.1 on 2022-01-24 05:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mstr_recipe',
            fields=[
                ('meal_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Recipe Title')),
                ('rec_url', models.URLField(verbose_name='Recipe URL')),
                ('vegan', models.BooleanField(verbose_name='Vegan')),
                ('vegetarian', models.BooleanField(verbose_name='Vegetarian')),
                ('meal_time', models.CharField(choices=[('bk', 'Breakfast'), ('lu', 'Lunch'), ('di', 'Dinner'), ('de', 'Dessert'), ('sn', 'Snack')], max_length=2, verbose_name='Meal Type')),
                ('dish_type', models.CharField(choices=[('sp', 'Soup'), ('bk', 'Baked Dishes'), ('pa', 'Pasta Dishes'), ('cu', 'Curry Dishes'), ('ca', 'Cassarole Dishes'), ('st', 'Stews'), ('sa', 'Salad'), ('lt', 'Light Dishes'), ('na', 'None of those')], max_length=2, verbose_name='Dish Type')),
                ('cooking_method', models.CharField(choices=[('st', 'Stovetop'), ('mi', 'Microwave'), ('gr', 'Grill'), ('ov', 'Oven'), ('pr', 'Pressure Cooker'), ('af', 'Air Fryer')], max_length=2, verbose_name='Cooking Method')),
                ('cooking_time', models.CharField(choices=[('20', 'Less Than 20 Minutes'), ('40', '20 to 40 Minutes'), ('60', '40 to 60 Minutes'), ('61', 'Over 60 Minutes')], max_length=2, verbose_name='Cooking Time')),
                ('times_selected', models.PositiveIntegerField(default=0, verbose_name='Number of times Selected')),
                ('upvote', models.PositiveIntegerField(default=0, verbose_name='Would Make Again')),
                ('downvote', models.PositiveIntegerField(default=0, verbose_name='Would Not Make Again')),
            ],
        ),
        migrations.AlterField(
            model_name='raw_recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Recipe Title'),
        ),
        migrations.CreateModel(
            name='recipe_taxonomy',
            fields=[
                ('taxonomy_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meals.mstr_recipe')),
                ('learned_words', models.JSONField(default=None, verbose_name='Learned Taxonomy')),
                ('correct_words', models.JSONField(default=None, verbose_name='Word Up Votes')),
                ('wrong_words', models.JSONField(default=None, verbose_name='Word Down Votes')),
            ],
        ),
        migrations.CreateModel(
            name='recipe_sims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compare_id', models.CharField(max_length=32, verbose_name='Comparison Recipe ID')),
                ('sim_score', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Simularity Score')),
                ('agree', models.PositiveIntegerField(default=0, verbose_name='Agreement Votes')),
                ('disagree', models.PositiveIntegerField(default=0, verbose_name='Disagreement Votes')),
                ('sim_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meals.mstr_recipe')),
            ],
        ),
    ]
