# Generated by Django 4.0.1 on 2022-02-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_raw_recipe_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstr_recipe',
            name='found_words',
            field=models.JSONField(default=None, verbose_name='Found Words'),
        ),
        migrations.AddField(
            model_name='raw_recipe',
            name='mstr_flag',
            field=models.BooleanField(default=False, verbose_name='Master Flag'),
        ),
    ]
