# Generated by Django 4.0.1 on 2022-02-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_mstr_recipe_found_words_raw_recipe_mstr_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_recipe',
            name='mstr_flag',
            field=models.BooleanField(default=False),
        ),
    ]
