# Generated by Django 4.0.1 on 2022-02-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_raw_recipe_mstr_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_recipe',
            name='error_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='raw_recipe',
            name='rec_url',
            field=models.URLField(unique=True, verbose_name='Recpie URL'),
        ),
    ]
