# Generated by Django 4.0.1 on 2022-02-05 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_raw_recipe_error_flag_alter_raw_recipe_rec_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='meal_id',
            field=models.UUIDField(default=uuid.UUID('e599875d-865d-11ec-9e42-085bd652e6e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
