# Generated by Django 4.0.1 on 2022-02-05 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_mstr_recipe_meal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='meal_id',
            field=models.UUIDField(default=uuid.UUID('0ea3c0b9-86cd-11ec-9563-085bd652e6e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
