# Generated by Django 4.0.1 on 2022-02-05 23:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_alter_mstr_recipe_meal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='meal_id',
            field=models.UUIDField(default=uuid.UUID('b1a0bfb4-86df-11ec-8abd-085bd652e6e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
