# Generated by Django 4.0.1 on 2022-02-18 01:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_alter_mstr_recipe_meal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='cooking_method',
            field=models.CharField(choices=[('st', 'Stovetop'), ('mi', 'Microwave'), ('bl', 'Blender'), ('gr', 'Grill'), ('ov', 'Oven'), ('pr', 'Pressure Cooker'), ('af', 'Air Fryer')], max_length=2, verbose_name='Cooking Method'),
        ),
        migrations.AlterField(
            model_name='mstr_recipe',
            name='dish_type',
            field=models.CharField(choices=[('sp', 'Soup'), ('bk', 'Baked Dishes'), ('pa', 'Pasta Dishes'), ('cu', 'Curry Dishes'), ('ca', 'Cassarole Dishes'), ('st', 'Stews'), ('sa', 'Salad'), ('lt', 'Light Dishes'), ('sm', 'Smoothie'), ('na', 'None of those')], max_length=2, verbose_name='Dish Type'),
        ),
        migrations.AlterField(
            model_name='mstr_recipe',
            name='meal_id',
            field=models.UUIDField(default=uuid.UUID('7567b84e-905a-11ec-ae0b-085bd652e6e3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='raw_recipe',
            name='cooking_method',
            field=models.CharField(choices=[('st', 'Stovetop'), ('mi', 'Microwave'), ('bl', 'Blender'), ('gr', 'Grill'), ('ov', 'Oven'), ('pr', 'Pressure Cooker'), ('af', 'Air Fryer')], max_length=2, verbose_name='Cooking Method'),
        ),
        migrations.AlterField(
            model_name='raw_recipe',
            name='dish_type',
            field=models.CharField(choices=[('sp', 'Soup'), ('bk', 'Baked Dishes'), ('pa', 'Pasta Dishes'), ('cu', 'Curry Dishes'), ('ca', 'Cassarole Dishes'), ('st', 'Stews'), ('sa', 'Salad'), ('lt', 'Light Dishes'), ('sm', 'Smoothie'), ('na', 'None of those')], max_length=2, verbose_name='Dish Type'),
        ),
    ]
