# Generated by Django 4.0.1 on 2022-02-18 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_alter_mstr_recipe_cooking_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='meal_id',
            field=models.UUIDField(default=uuid.UUID('fe67eea1-905a-11ec-8ea0-085bd652e6e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
