# Generated by Django 4.0.1 on 2022-02-18 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_alter_mstr_recipe_meal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='meal_id',
            field=models.UUIDField(default=uuid.UUID('19f73b3d-906c-11ec-b4e0-085bd652e6e3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='raw_recipe',
            index=models.Index(fields=['mstr_flag', 'error_flag'], name='meals_raw_r_mstr_fl_c3f387_idx'),
        ),
    ]
