# Generated by Django 4.0.1 on 2022-02-18 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_alter_mstr_recipe_meal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='meal_id',
            field=models.UUIDField(default=uuid.UUID('2c2bdd34-906f-11ec-af3b-085bd652e6e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
