# Generated by Django 4.0.1 on 2022-02-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_alter_mstr_recipe_meal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='meal_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
