# Generated by Django 4.0.1 on 2022-02-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_alter_mstr_recipe_meal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='cooking_method',
            field=models.CharField(choices=[('st', 'Stovetop'), ('mi', 'Microwave'), ('bl', 'Blender'), ('gr', 'Grill'), ('ov', 'Oven'), ('pr', 'Pressure Cooker'), ('sc', 'Slow Cooker'), ('af', 'Air Fryer')], max_length=2, verbose_name='Cooking Method'),
        ),
        migrations.AlterField(
            model_name='raw_recipe',
            name='cooking_method',
            field=models.CharField(choices=[('st', 'Stovetop'), ('mi', 'Microwave'), ('bl', 'Blender'), ('gr', 'Grill'), ('ov', 'Oven'), ('pr', 'Pressure Cooker'), ('sc', 'Slow Cooker'), ('af', 'Air Fryer')], max_length=2, verbose_name='Cooking Method'),
        ),
        migrations.AlterField(
            model_name='recipe_sims',
            name='compare_id',
            field=models.UUIDField(verbose_name='Comparison Recipe ID'),
        ),
    ]
