# Generated by Django 4.0.1 on 2022-02-27 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_alter_mstr_recipe_cooking_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_sims',
            name='sim_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mstr_recipe'),
        ),
    ]
