# Generated by Django 4.0.1 on 2022-02-27 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0018_alter_recipe_sims_sim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_sims',
            name='compare_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_meal', to='meals.mstr_recipe'),
        ),
    ]
