# Generated by Django 4.0.1 on 2022-02-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0019_alter_recipe_sims_compare_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_sims',
            old_name='compare_id',
            new_name='compare',
        ),
        migrations.RenameField(
            model_name='recipe_sims',
            old_name='sim_id',
            new_name='sim',
        ),
    ]
