# Generated by Django 4.0.1 on 2022-03-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0021_delete_recipe_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstr_recipe',
            name='protein_type',
            field=models.CharField(choices=[('be', 'Beef'), ('ch', 'Chicken'), ('pb', 'Plant Based'), ('se', 'Fish/Shellfish'), ('pk', 'Pork'), ('na', 'None'), ('ot', 'Other')], default='na', max_length=2, verbose_name='Main Protein'),
        ),
        migrations.AddField(
            model_name='raw_recipe',
            name='protein_type',
            field=models.CharField(choices=[('be', 'Beef'), ('ch', 'Chicken'), ('pb', 'Plant Based'), ('se', 'Fish/Shellfish'), ('pk', 'Pork'), ('na', 'None'), ('ot', 'Other')], default='na', max_length=2, verbose_name='Main Protein'),
        ),
        migrations.AlterField(
            model_name='mstr_recipe',
            name='cooking_method',
            field=models.CharField(choices=[('st', 'Stovetop'), ('mi', 'Microwave'), ('bl', 'Blender'), ('gr', 'Grill'), ('ov', 'Oven'), ('pr', 'Pressure Cooker'), ('sc', 'Slow Cooker'), ('af', 'Air Fryer'), ('ot', 'Other')], max_length=2, verbose_name='Cooking Method'),
        ),
        migrations.AlterField(
            model_name='raw_recipe',
            name='cooking_method',
            field=models.CharField(choices=[('st', 'Stovetop'), ('mi', 'Microwave'), ('bl', 'Blender'), ('gr', 'Grill'), ('ov', 'Oven'), ('pr', 'Pressure Cooker'), ('sc', 'Slow Cooker'), ('af', 'Air Fryer'), ('ot', 'Other')], max_length=2, verbose_name='Cooking Method'),
        ),
    ]
