# Generated by Django 4.0.1 on 2022-03-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0022_mstr_recipe_protein_type_raw_recipe_protein_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='cooking_method',
            field=models.CharField(choices=[('st', 'Stovetop'), ('mi', 'Microwave'), ('bl', 'Blender'), ('gr', 'Grill'), ('ov', 'Oven'), ('pr', 'Pressure Cooker'), ('sc', 'Slow Cooker'), ('af', 'Air Fryer'), ('ra', 'Raw/Uncooked'), ('ot', 'Other')], max_length=2, verbose_name='Cooking Method'),
        ),
        migrations.AlterField(
            model_name='mstr_recipe',
            name='meal_time',
            field=models.CharField(choices=[('bk', 'Breakfast'), ('lu', 'Lunch'), ('di', 'Dinner'), ('sd', 'Side Dish'), ('de', 'Dessert'), ('sn', 'Snack')], max_length=2, verbose_name='Meal Type'),
        ),
        migrations.AlterField(
            model_name='raw_recipe',
            name='cooking_method',
            field=models.CharField(choices=[('st', 'Stovetop'), ('mi', 'Microwave'), ('bl', 'Blender'), ('gr', 'Grill'), ('ov', 'Oven'), ('pr', 'Pressure Cooker'), ('sc', 'Slow Cooker'), ('af', 'Air Fryer'), ('ra', 'Raw/Uncooked'), ('ot', 'Other')], max_length=2, verbose_name='Cooking Method'),
        ),
        migrations.AlterField(
            model_name='raw_recipe',
            name='meal_time',
            field=models.CharField(choices=[('bk', 'Breakfast'), ('lu', 'Lunch'), ('di', 'Dinner'), ('sd', 'Side Dish'), ('de', 'Dessert'), ('sn', 'Snack')], max_length=2, verbose_name='Meal Type'),
        ),
    ]
