# Generated by Django 4.0.1 on 2022-09-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0023_alter_mstr_recipe_cooking_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='meal_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
            ],
        ),
        migrations.CreateModel(
            name='mstr_recipe_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveBigIntegerField(default=1, verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal_item')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mstr_recipe')),
            ],
            options={
                'unique_together': {('meal', 'item')},
            },
        ),
    ]
