# Generated by Django 4.0.1 on 2022-09-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0025_mstr_recipe_list_uom_alter_mstr_recipe_list_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_item',
            name='item_location',
            field=models.CharField(choices=[('un', 'Unknown'), ('pr', 'Produce'), ('dr', 'Dry Goods'), ('cv', 'Canned Veg'), ('cm', 'Canned Meat'), ('sp', 'Soups'), ('in', 'International'), ('fr', 'Frozen'), ('sp', 'Spices'), ('dl', 'Deli/Cheese'), ('da', 'Dairy'), ('mt', 'Meat/Seafood')], default='un', max_length=2, verbose_name='Item Section'),
        ),
        migrations.AlterField(
            model_name='mstr_recipe_list',
            name='uom',
            field=models.CharField(choices=[('qt', ''), ('ts', 'Tsp'), ('tb', 'Tbsp'), ('cu', 'Cup'), ('oz', 'Ounces'), ('lb', 'Pounds'), ('ml', 'Milliliter'), ('ll', 'Liter')], default='qt', max_length=2, verbose_name='Unit of Measure'),
        ),
    ]
