# Generated by Django 4.0.1 on 2022-09-22 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0026_meal_item_item_location_alter_mstr_recipe_list_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_log',
            fields=[
                ('version', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Version')),
                ('implemented', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='mstr_recipe',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.CharField(choices=[('ad', 'Added'), ('ch', 'Changed'), ('de', 'Deprecated'), ('re', 'Removed'), ('fx', 'Fixed'), ('se', 'Security')], max_length=2, verbose_name='Change Type')),
                ('change_desc', models.CharField(max_length=256, verbose_name='Change Description')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.change_log')),
            ],
        ),
    ]
