# Generated by Django 4.0.1 on 2022-09-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0027_change_log_mstr_recipe_dummy_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_item',
            name='poss_duplicate',
            field=models.BooleanField(default=False, verbose_name='Possible Duplicate'),
        ),
    ]
