# Generated by Django 4.0.1 on 2022-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0028_meal_item_poss_duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_item',
            name='item_location',
            field=models.CharField(choices=[('un', 'Unknown'), ('pr', 'Produce'), ('dr', 'Dry Goods'), ('co', 'Condiments/Oils'), ('pi', 'Pickled/Olives'), ('ge', 'General Grocery'), ('cv', 'Canned Veg'), ('cm', 'Canned Meat'), ('so', 'Soups'), ('in', 'International'), ('fr', 'Frozen'), ('sp', 'Spices'), ('dl', 'Deli/Cheese'), ('da', 'Dairy'), ('mt', 'Meat/Seafood'), ('ho', 'Household Item')], default='un', max_length=2, verbose_name='Item Section'),
        ),
        migrations.AlterField(
            model_name='mstr_recipe',
            name='dummy',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
