# Generated by Django 4.0.1 on 2022-11-21 01:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0029_alter_meal_item_item_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mstr_search',
            fields=[
                ('meal_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meals.mstr_recipe')),
                ('raw_words', models.TextField(verbose_name='Recipe Text')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='mstr_search',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='meals_mstr__search__6017fb_gin'),
        ),
    ]
