# Generated by Django 4.0.1 on 2023-01-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0033_rename_downvote_mstr_recipe_reviewnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstr_recipe',
            name='reviewnum',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Reviews'),
        ),
        migrations.AlterField(
            model_name='mstr_recipe',
            name='reviewsum',
            field=models.PositiveIntegerField(default=0, verbose_name='Sum of Reviews'),
        ),
    ]
