# Generated by Django 4.0.1 on 2023-01-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0034_alter_mstr_recipe_reviewnum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mstr_recipe',
            old_name='reviewnum',
            new_name='numreview',
        ),
        migrations.RenameField(
            model_name='mstr_recipe',
            old_name='reviewsum',
            new_name='sumreview',
        ),
    ]
