# Generated by Django 4.0.1 on 2024-02-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0035_rename_reviewnum_mstr_recipe_numreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstr_recipe',
            name='ai_recipe',
            field=models.BooleanField(default=False, verbose_name='AImade'),
        ),
        migrations.AddField(
            model_name='raw_recipe',
            name='ai_recipe',
            field=models.BooleanField(default=False, verbose_name='AImade'),
        ),
    ]
