# Generated by Django 4.0.1 on 2023-07-10 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stewpot', '0002_meal_posting_share_meal_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_posting',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
