# Generated by Django 4.0.1 on 2024-02-04 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0036_mstr_recipe_ai_recipe_raw_recipe_ai_recipe'),
        ('stewpot', '0003_meal_posting_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_html',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_id', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mstr_recipe')),
            ],
        ),
    ]
